FROM mongo:4.4.1
MAINTAINER m0as <lasm.landry@gmail.com>

WORKDIR /

COPY * .

RUN sh setup.sh && rm setup.sh

VOLUME /backup

# Mongodb env
ENV MONGO_URI 'mongodb://mongo:27017'

# S3 env
ENV TARGET_S3_FOLDER 'mongodump'
ENV AWS_ACCESS_KEY_ID '**None**'
ENV AWS_SECRET_ACCESS_KEY '**None**'
ENV ENDPOINT_URL '**None**'
ENV BUCKET_NAME '**None**'
ENV ACL 'private'

# Other env
ENV CRON_SCHEDULE '**None**'
ENV TARGET_FOLDER '/backup'


CMD ["sh", "run.sh"]
